Define the Problem
Prepare Data
Evaluate some Algorithms
Improve Results
Present Results

In [1]:
# Load libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [2]:
# Load the iris data set from remote url
def loadDatasetFromUrl():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
    #giturl = "https://raw.githubusercontent.com/abhishekanand/datasets/master/data/iris.data" # Use raw URL
    columnattribute = ['sepal-length (cm)', 'sepal-width (cm)', 'petal-length (cm)', 'petal-width (cm)', 'species']
    return pd.read_csv(url, names=columnattribute)
    #return pd.read_csv(giturl, names=columnattribute)

In [3]:
iris_dataset = loadDatasetFromUrl()
iris_dataset.head() # #peek at the data

,sepal-length (cm),sepal-width (cm),petal-length (cm),petal-width (cm),species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [4]:
iris_dataset['species'] = iris_dataset['species'].str.replace('Iris-','')
iris_dataset.head()

,sepal-length (cm),sepal-width (cm),petal-length (cm),petal-width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

#  Evaluate some Algorithms
Separate out a validation dataset.
Set-up the test harness to use 10-fold cross validation.
Build 5 different models to predict species from flower measurements
Select the best model.

Here we have the types of classification algorithms in Machine Learning:

Linear Classifiers: Logistic Regression, Naive Bayes Classifier
Support Vector Machines
Decision Trees
Boosted Trees
Random Forest
Neural Networks
Nearest Neighbor

In [5]:
from sklearn import model_selection

In [6]:
# Split-out validation dataset
array = iris_dataset.values
X = array[:,0:4]
Y = array[:,4]
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [7]:
# from sklearn import linear_model
from sklearn.linear_model import LogisticRegression

In [8]:
#creating Model
logreg = LogisticRegression()

In [9]:
# Train Model
logreg.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [10]:
#Predicting the test set results 
Y_pred = logreg.predict(X_validation)

In [11]:
Y_validation

array(['virginica', 'versicolor', 'setosa', 'versicolor', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'setosa', 'virginica', 'setosa',
       'versicolor', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica'],
      dtype=object)

In [12]:
Y_pred

array(['virginica', 'virginica', 'setosa', 'virginica', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'virginica', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica'],
      dtype=object)

In [13]:
result = pd.DataFrame( {'X_validation':list( X_validation),'Y_validation': Y_validation, 'Y_pred': Y_pred}, columns=['X_validation','Y_validation', 'Y_pred'])

In [14]:
result

            X_validation Y_validation      Y_pred
0   [5.9, 3.0, 5.1, 1.8]    virginica   virginica
1   [5.4, 3.0, 4.5, 1.5]   versicolor   virginica
2   [5.0, 3.5, 1.3, 0.3]       setosa      setosa
3   [5.6, 3.0, 4.5, 1.5]   versicolor   virginica
4   [4.9, 2.5, 4.5, 1.7]    virginica   virginica
5   [4.5, 2.3, 1.3, 0.3]       setosa      setosa
6   [6.9, 3.1, 4.9, 1.5]   versicolor  versicolor
7   [5.6, 2.7, 4.2, 1.3]   versicolor  versicolor
8   [4.8, 3.4, 1.6, 0.2]       setosa      setosa
9   [6.4, 3.2, 4.5, 1.5]   versicolor  versicolor
10  [6.7, 3.0, 5.0, 1.7]   versicolor   virginica
11  [6.0, 3.4, 4.5, 1.6]   versicolor   virginica
12  [5.2, 4.1, 1.5, 0.1]       setosa      setosa
13  [7.2, 3.6, 6.1, 2.5]    virginica   virginica
14  [5.2, 3.4, 1.4, 0.2]       setosa      setosa
15  [5.9, 3.2, 4.8, 1.8]   versicolor   virginica
16  [6.7, 2.5, 5.8, 1.8]    virginica   virginica
17  [6.4, 3.1, 5.5, 1.8]    virginica   virginica
18  [5.1, 3.8, 1.6, 0.2]       setosa      setosa
19  [4.9, 3.1, 1.5, 0.1]       setosa      setosa
20  [5.8, 2.7, 3.9, 1.2]   versicolor  versicolor
21  [6.9, 3.2, 5.7, 2.3]    virginica   virginica
22  [6.1, 2.9, 4.7, 1.4]   versicolor  versicolor
23  [6.0, 2.2, 5.0, 1.5]    virginica   virginica
24  [7.2, 3.0, 5.8, 1.6]    virginica  versicolor
25  [6.0, 3.0, 4.8, 1.8]    virginica   virginica
26  [6.2, 2.9, 4.3, 1.3]   versicolor  versicolor
27  [5.5, 2.4, 3.8, 1.1]   versicolor  versicolor
28  [5.8, 2.7, 5.1, 1.9]    virginica   virginica
29  [6.7, 3.1, 5.6, 2.4]    virginica   virginica

In [16]:
result['Out'] = result.apply(lambda x: True if x['Y_validation'] == x['Y_pred'] else False, axis=1)

In [17]:
result

            X_validation Y_validation      Y_pred    Out
0   [5.9, 3.0, 5.1, 1.8]    virginica   virginica   True
1   [5.4, 3.0, 4.5, 1.5]   versicolor   virginica  False
2   [5.0, 3.5, 1.3, 0.3]       setosa      setosa   True
3   [5.6, 3.0, 4.5, 1.5]   versicolor   virginica  False
4   [4.9, 2.5, 4.5, 1.7]    virginica   virginica   True
5   [4.5, 2.3, 1.3, 0.3]       setosa      setosa   True
6   [6.9, 3.1, 4.9, 1.5]   versicolor  versicolor   True
7   [5.6, 2.7, 4.2, 1.3]   versicolor  versicolor   True
8   [4.8, 3.4, 1.6, 0.2]       setosa      setosa   True
9   [6.4, 3.2, 4.5, 1.5]   versicolor  versicolor   True
10  [6.7, 3.0, 5.0, 1.7]   versicolor   virginica  False
11  [6.0, 3.4, 4.5, 1.6]   versicolor   virginica  False
12  [5.2, 4.1, 1.5, 0.1]       setosa      setosa   True
13  [7.2, 3.6, 6.1, 2.5]    virginica   virginica   True
14  [5.2, 3.4, 1.4, 0.2]       setosa      setosa   True
15  [5.9, 3.2, 4.8, 1.8]   versicolor   virginica  False
16  [6.7, 2.5, 5.8, 1.8]    virginica   virginica   True
17  [6.4, 3.1, 5.5, 1.8]    virginica   virginica   True
18  [5.1, 3.8, 1.6, 0.2]       setosa      setosa   True
19  [4.9, 3.1, 1.5, 0.1]       setosa      setosa   True
20  [5.8, 2.7, 3.9, 1.2]   versicolor  versicolor   True
21  [6.9, 3.2, 5.7, 2.3]    virginica   virginica   True
22  [6.1, 2.9, 4.7, 1.4]   versicolor  versicolor   True
23  [6.0, 2.2, 5.0, 1.5]    virginica   virginica   True
24  [7.2, 3.0, 5.8, 1.6]    virginica  versicolor  False
25  [6.0, 3.0, 4.8, 1.8]    virginica   virginica   True
26  [6.2, 2.9, 4.3, 1.3]   versicolor  versicolor   True
27  [5.5, 2.4, 3.8, 1.1]   versicolor  versicolor   True
28  [5.8, 2.7, 5.1, 1.9]    virginica   virginica   True
29  [6.7, 3.1, 5.6, 2.4]    virginica   virginica   True

In [18]:
result['Out'].value_counts()

True     24
False     6
Name: Out, dtype: int64

In [19]:
logreg.score(X_validation,Y_validation)

0.8

In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_validation, Y_pred)
print(confusion_matrix)

[[ 7  0  0]
 [ 0  7  5]
 [ 0  1 10]]

In [23]:
from sklearn.metrics import classification_report
print(classification_report(Y_validation, Y_pred))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00         7
 versicolor       0.88      0.58      0.70        12
  virginica       0.67      0.91      0.77        11

avg / total       0.83      0.80      0.80        30